name: bsev
description: Useful to aid in the use of BloC pattern with dependency injection
version: 0.0.5
author: RafaelBarbosatec<rafaelbarbosatec@gmail.com>
homepage: https://github.com/RafaelBarbosatec/tutorial_coach_mark

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  rxdart: ^0.21.0
  injector: ^1.0.8
  provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
